/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tokokomputer.form;

import com.tokokomputer.controller.Koneksi;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class layanan_jual extends javax.swing.JFrame {
   
    public void kliktable_layananpenjualan(){
        int baris =tampil_barang.getSelectedRow();
        cbNmBarang.setText((String)tampil_barang.getValueAt(baris, 1));
        txtjenis.setText((String)tampil_barang.getValueAt(baris, 2));
        txtHarga.setText((String) tampil_barang.getValueAt (baris,3));
        
       
    }
    public void tampil() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Id Barang");
        tbl.addColumn("Nama Barang");
        tbl.addColumn("Jenis Produk");
        tbl.addColumn("Harga Produk");
        try {
            String sql = "SELECT id_barang,nama_barang,jenis_produk,harga_produk FROM barang";
            java.sql.Connection conn = (Connection) Koneksi.getKoneksi();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                tbl.addRow(new Object[]{
                    res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4),});
            }
            tampil_barang.setModel(tbl);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    public void tampilTable(){
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("Nama Barang");
        tabel.addColumn("Harga Satuan");
        tabel.addColumn("Jumlah Beli");
        tabel.addColumn("Total");
        
        tblKeranjang.setModel(tabel);
                
    }
    
    public void hitungTotalHarga(){
        DefaultTableModel model = (DefaultTableModel) tblKeranjang.getModel();
        int totalHarga = 0;
            
        for(int j = 0; j < tblKeranjang.getRowCount(); j++){
            totalHarga = totalHarga + Integer.parseInt(model.getValueAt(j, 4).toString());     
        }

        txtJmlHarga.setText(String.valueOf(totalHarga));
    }
    
    public layanan_jual() {
        initComponents();
        tampilTable();
        tampil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        txtjenis = new javax.swing.JTextField();
        txtJmlHarga = new javax.swing.JTextField();
        txtJmlKembalian = new javax.swing.JTextField();
        btnHapusItem = new javax.swing.JButton();
        btnHitungJmlKembalian = new javax.swing.JButton();
        txtJmlBayar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnBatal = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKeranjang = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnHitungJmlHarga1 = new javax.swing.JButton();
        btnEditItem = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtJmlBeli = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tampil_barang = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        cbNmBarang = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Kasir Sederhana");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nama Barang");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Jenis Barang");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Total");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Kuantitas");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Kembalian");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        txtHarga.setEditable(false);
        txtHarga.setBackground(new java.awt.Color(102, 255, 255));
        txtHarga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtHarga.setText("0");
        getContentPane().add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 140, -1));

        txtjenis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtjenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjenisActionPerformed(evt);
            }
        });
        txtjenis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtjenisKeyReleased(evt);
            }
        });
        getContentPane().add(txtjenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 140, -1));

        txtJmlHarga.setEditable(false);
        txtJmlHarga.setBackground(new java.awt.Color(102, 255, 255));
        txtJmlHarga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtJmlHarga.setText("0");
        txtJmlHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJmlHargaActionPerformed(evt);
            }
        });
        getContentPane().add(txtJmlHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 140, -1));

        txtJmlKembalian.setEditable(false);
        txtJmlKembalian.setBackground(new java.awt.Color(102, 255, 255));
        txtJmlKembalian.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtJmlKembalian.setText("0");
        txtJmlKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJmlKembalianActionPerformed(evt);
            }
        });
        getContentPane().add(txtJmlKembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 140, -1));

        btnHapusItem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHapusItem.setText("Hapus Item");
        btnHapusItem.setEnabled(false);
        btnHapusItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusItemActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapusItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 110, -1));

        btnHitungJmlKembalian.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHitungJmlKembalian.setText("Hitung Jumlah Kembalian");
        btnHitungJmlKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungJmlKembalianActionPerformed(evt);
            }
        });
        getContentPane().add(btnHitungJmlKembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, -1, -1));

        txtJmlBayar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtJmlBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtJmlBayarKeyReleased(evt);
            }
        });
        getContentPane().add(txtJmlBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 140, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Tunai");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));

        btnBatal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBatal.setText("Batalkan Transaksi");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, 150, -1));

        btnKeluar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 100, -1));

        btnCetak.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCetak.setText("Cetak Struk");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });
        getContentPane().add(btnCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, -1, -1));

        tblKeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKeranjang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKeranjangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblKeranjang);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 550, 500));

        btnTambah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTambah.setText("Tambah Ke Keranjang");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 190, -1));

        btnHitungJmlHarga1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHitungJmlHarga1.setText("Hitung Jumlah Harga");
        btnHitungJmlHarga1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungJmlHarga1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnHitungJmlHarga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 185, -1));

        btnEditItem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEditItem.setText("Edit Item");
        btnEditItem.setEnabled(false);
        btnEditItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditItemActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 110, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

        txtJmlBeli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtJmlBeli.setText("0");
        txtJmlBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJmlBeliActionPerformed(evt);
            }
        });
        txtJmlBeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtJmlBeliKeyReleased(evt);
            }
        });
        getContentPane().add(txtJmlBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 140, -1));

        tampil_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tampil_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tampil_barangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tampil_barang);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 40, 530, 130));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Harga Barang");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        cbNmBarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbNmBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNmBarangActionPerformed(evt);
            }
        });
        cbNmBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbNmBarangKeyReleased(evt);
            }
        });
        getContentPane().add(cbNmBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 140, -1));

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1130, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtjenisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjenisKeyReleased
        // TODO add your handling code here:
//        if(txtJmlBeli.getText().equals("") || txtJmlBeli.getText().equals("0")){
//           JOptionPane.showMessageDialog(rootPane, "Jumlah Beli Tidak Boleh Kosong!!!"); 
//           txtJmlBeli.setText("1");
//        }else {
//            int jumlahBeli = Integer.parseInt(txtJmlBeli.getText());
//            int harga = Integer.parseInt(txtHarga.getText());
//            int jumlahHarga = harga * jumlahBeli;
//            txtJmlHarga.setText(String.valueOf(jumlahHarga));
//        }
        
    }//GEN-LAST:event_txtjenisKeyReleased

    private void txtJmlBayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJmlBayarKeyReleased
        
        if(txtJmlBayar.getText().equals("") || txtJmlBayar.getText().equals("0")){
           JOptionPane.showMessageDialog(rootPane, "Jumlah Bayar Tidak Boleh Kosong!!!"); 
        } else {
            int jharga,bayar,hasil;
        
            jharga=Integer.parseInt(txtJmlHarga.getText());
            bayar=Integer.parseInt(txtJmlBayar.getText());
            hasil= bayar-jharga;
            txtJmlKembalian.setText(String.valueOf(hasil));
        }
    }//GEN-LAST:event_txtJmlBayarKeyReleased

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        txtjenis.setText("");
        txtHarga.setText("0");
        txtjenis.setText("0");
        txtJmlHarga.setText("0");
        txtJmlBayar.setText("");
        txtJmlKembalian.setText("0");
        
        DefaultTableModel model = (DefaultTableModel) tblKeranjang.getModel();
        for( int i = model.getRowCount() - 1; i >= 0; i-- ) {
            model.removeRow(i);
        }
        
        btnEditItem.setEnabled(false);
        btnHapusItem.setEnabled(false);
        btnTambah.setEnabled(true);
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnHapusItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusItemActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblKeranjang.getModel();
        
        try{
            int SelectedRowIndex = tblKeranjang.getSelectedRow();
            
            int jmlHarga = Integer.parseInt(tblKeranjang.getValueAt(SelectedRowIndex, 3).toString());
            
            model.removeRow(SelectedRowIndex);
            
            hitungTotalHarga();
                    
            txtHarga.setText("");
            txtjenis.setText("");
            txtjenis.setText("");
            
            btnEditItem.setEnabled(false);
            btnHapusItem.setEnabled(false);
            btnTambah.setEnabled(true);

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnHapusItemActionPerformed

    private void btnHitungJmlKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungJmlKembalianActionPerformed
        Double jharga,bayar,hasil;
        
        jharga=Double.parseDouble(txtJmlHarga.getText());
        bayar=Double.parseDouble(txtJmlBayar.getText());
        hasil=bayar-jharga;
        txtJmlKembalian.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btnHitungJmlKembalianActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed

        if(txtJmlBayar.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Lakukan Proses Pembayaran Terlebih Dahulu!!!");
        } else {
            try{
                DefaultTableModel model = (DefaultTableModel) tblKeranjang.getModel();
                String totalHarga = txtJmlHarga.getText();
                String tunai = txtJmlBayar.getText();
                String kembalian = txtJmlKembalian.getText();
                String[] judul = {"Nama Barang", "Harga", "Jumlah", "Total"};
                String[][] isi = new String[tblKeranjang.getRowCount()][tblKeranjang.getColumnCount()];

                for(int i = 0; i < tblKeranjang.getRowCount(); i++){
                    for(int j = 0; j < tblKeranjang.getColumnCount(); j++){
                        isi[i][j] = model.getValueAt(i, j).toString();
                    }
                }

                Cetak tabel = new Cetak(judul, isi, tblKeranjang.getRowCount(), tblKeranjang.getColumnCount(), totalHarga, tunai, kembalian);

                JOptionPane.showMessageDialog(rootPane, "Transaksi Selesai!!..");

                txtjenis.setText("");
                txtHarga.setText("0");
                txtjenis.setText("0");
                txtJmlHarga.setText("0");
                txtJmlBayar.setText("");
                txtJmlKembalian.setText("0");

                for(int l = model.getRowCount() - 1; l >= 0; l-- ) {
                    model.removeRow(l);
                }

                btnEditItem.setEnabled(false);
                btnHapusItem.setEnabled(false);
                btnTambah.setEnabled(true);
            
            }catch(Exception e){
                System.out.println(e);
            } 
        }
        
    }//GEN-LAST:event_btnCetakActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        
        if(cbNmBarang.getText().equals("-- Pilih Barang --")){
            JOptionPane.showMessageDialog(rootPane, "Pilih Barang terlebih dahulu!!!");
        } else {
            DefaultTableModel model = (DefaultTableModel) tblKeranjang.getModel();
            int jmlHargaBarang = Integer.parseInt(txtHarga.getText()) * Integer.parseInt(txtJmlBeli.getText());
//            model.addRow(new Object[] {cbNmBarang.getText(),txtjenis.getText()});
            model.addRow(new Object[] {cbNmBarang.getText(), txtHarga.getText(), txtjenis.getText(), jmlHargaBarang});

            hitungTotalHarga();
           
          cbNmBarang.setText("");
          txtHarga.setText("");
          txtjenis.setText("");
          
            
          
        }
        
        
    }//GEN-LAST:event_btnTambahActionPerformed

    private void tblKeranjangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKeranjangMouseClicked
        int table = tblKeranjang.getSelectedRow();
        
        String a = tblKeranjang.getValueAt(table, 0).toString();
        String b = tblKeranjang.getValueAt(table, 1).toString();
        String c = tblKeranjang.getValueAt(table, 2).toString();
        
        txtjenis.setText(a);
        txtHarga.setText(b);
        txtjenis.setText(c);
        
        btnEditItem.setEnabled(true);
        btnHapusItem.setEnabled(true);
        btnTambah.setEnabled(false);
    }//GEN-LAST:event_tblKeranjangMouseClicked

    private void btnHitungJmlHarga1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungJmlHarga1ActionPerformed
        Double harga,jbeli,hasil;
        harga=Double.parseDouble(txtHarga.getText());
        jbeli=Double.parseDouble(txtJmlBeli.getText());
        hasil=harga*jbeli;
        txtJmlHarga.setText(String.valueOf(hasil));      
    }//GEN-LAST:event_btnHitungJmlHarga1ActionPerformed

    private void btnEditItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditItemActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblKeranjang.getModel();
        int i = tblKeranjang.getSelectedRow();
                
        if(i >= 0) 
        {
            model.setValueAt(txtjenis.getText(), i, 0);
            model.setValueAt(txtHarga.getText(), i, 1);
            model.setValueAt(txtjenis.getText(), i, 2);
           
            int jmlHargaBarang = Integer.parseInt(txtHarga.getText()) * Integer.parseInt(txtjenis.getText());
    
            model.setValueAt(jmlHargaBarang, i, 3);
            hitungTotalHarga();
            
            txtHarga.setText("");
            txtjenis.setText("");
            txtjenis.setText("");
            
            btnEditItem.setEnabled(false);
            btnHapusItem.setEnabled(false);
            btnTambah.setEnabled(true);
            
        }
        else{
            System.out.println("Update Error");
        }
    }//GEN-LAST:event_btnEditItemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtjenis.setText("");
        txtHarga.setText("");
        txtjenis.setText("");
        
        btnEditItem.setEnabled(false);
        btnHapusItem.setEnabled(false);
        btnTambah.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtJmlHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJmlHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJmlHargaActionPerformed

    private void txtJmlKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJmlKembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJmlKembalianActionPerformed

    private void txtJmlBeliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJmlBeliKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJmlBeliKeyReleased

    private void txtjenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjenisActionPerformed

    private void tampil_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tampil_barangMouseClicked
        kliktable_layananpenjualan();
    }//GEN-LAST:event_tampil_barangMouseClicked

    private void cbNmBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNmBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNmBarangActionPerformed

    private void cbNmBarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbNmBarangKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNmBarangKeyReleased

    private void txtJmlBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJmlBeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJmlBeliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(layanan_jual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(layanan_jual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(layanan_jual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(layanan_jual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new layanan_jual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnEditItem;
    private javax.swing.JButton btnHapusItem;
    private javax.swing.JButton btnHitungJmlHarga1;
    private javax.swing.JButton btnHitungJmlKembalian;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnTambah;
    private javax.swing.JTextField cbNmBarang;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tampil_barang;
    private javax.swing.JTable tblKeranjang;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJmlBayar;
    private javax.swing.JTextField txtJmlBeli;
    private javax.swing.JTextField txtJmlHarga;
    private javax.swing.JTextField txtJmlKembalian;
    private javax.swing.JTextField txtjenis;
    // End of variables declaration//GEN-END:variables
}
